### ISSUE TITLE
Swift 5.0 Support 

### ISSUE THREAD

**Issue by deepesh-vasthimal-cko** [Boilertalk/secp256k1.swift#11]
Hi All

I can see this does not build and fails with Nimble. Also its running on swift 4.0 version. Any plans to update to swift 5.0 ? 

<img width="1109" alt="Screenshot 2020-06-08 at 20 29 31" src="https://user-images.githubusercontent.com/59569588/84072239-c9a6ec00-a9c6-11ea-8b4a-950b91f110cf.png">

Thanks
Deepesh

**Comment by koraykoska** [comment]
Swift 5 is supported.
